import type { BuildingDef, BuildingId } from "./types";

export const BUILDINGS: Record<BuildingId, BuildingDef> = {
  habitat: {
    id: "habitat",
    name: "Habitat Dome",
    icon: "⌂",
    description: "Pressurised dome that houses colonists.",
    cost: { credits: 150, minerals: 50 },
    upkeep: { power: 2, water: 1 },
    output: {},
    housing: 6,
    workers: 0,
  },
  solar: {
    id: "solar",
    name: "Solar Array",
    icon: "☀",
    description: "Photovoltaic array. Vulnerable to dust storms.",
    cost: { credits: 100, minerals: 30 },
    upkeep: {},
    output: { power: 5 },
    workers: 0,
    terrainBonus: { ridge: { power: 2 } },
  },
  water_extractor: {
    id: "water_extractor",
    name: "Water Extractor",
    icon: "☃",
    description: "Drills subsurface ice and refines it into water.",
    cost: { credits: 120, minerals: 40 },
    upkeep: { power: 2 },
    output: { water: 3 },
    workers: 1,
    terrainBonus: { ice: { water: 3 } },
  },
  greenhouse: {
    id: "greenhouse",
    name: "Greenhouse",
    icon: "⚘",
    description: "Hydroponic farm producing food.",
    cost: { credits: 140, minerals: 40 },
    upkeep: { power: 1, water: 1 },
    output: { food: 3 },
    workers: 1,
  },
  oxygen_gen: {
    id: "oxygen_gen",
    name: "Oxygen Generator",
    icon: "♁",
    description: "Splits CO2 to generate breathable oxygen.",
    cost: { credits: 130, minerals: 50 },
    upkeep: { power: 2 },
    output: { oxygen: 3 },
    workers: 1,
  },
  mine: {
    id: "mine",
    name: "Mine",
    icon: "⛏",
    description:
      "Extracts minerals from the regolith. Surplus ore is sold off-world for a small credit trickle.",
    cost: { credits: 160, minerals: 20 },
    upkeep: { power: 2 },
    output: { minerals: 2, credits: 1 },
    workers: 2,
    terrainBonus: { ore: { minerals: 2 } },
  },
  lab: {
    id: "lab",
    name: "Research Lab",
    icon: "⚗",
    description: "Generates research points to unlock new technology.",
    cost: { credits: 200, minerals: 60 },
    upkeep: { power: 1 },
    output: { research: 1 },
    workers: 2,
  },
  foundry: {
    id: "foundry",
    name: "Alloy Foundry",
    icon: "⚒",
    description: "Smelts minerals into structural alloys.",
    cost: { credits: 250, minerals: 80 },
    upkeep: { power: 3, minerals: 3 },
    output: { alloys: 1 },
    workers: 2,
    requiresResearch: "alloy_metallurgy",
  },
  spaceport: {
    id: "spaceport",
    name: "Spaceport",
    icon: "✈",
    description:
      "Launch pad and orbital docks. Enables expansion beyond Mars in future updates.",
    cost: { credits: 600, minerals: 200, alloys: 20 },
    upkeep: { power: 4 },
    output: { credits: 5 },
    workers: 3,
    requiresResearch: "spaceflight",
  },
};

export const BUILDING_ORDER: BuildingId[] = [
  "habitat",
  "solar",
  "water_extractor",
  "greenhouse",
  "oxygen_gen",
  "mine",
  "lab",
  "foundry",
  "spaceport",
];
