import type { BuildingDef, BuildingId } from "./types";

// Upgrade tiers reused across most buildings. Two levels above base, each
// multiplies output by 1.5 and upkeep by 1.25.
const standardUpgrades = (creditsBase: number, alloysBase: number) => [
  {
    cost: { credits: creditsBase, alloys: alloysBase, minerals: alloysBase * 2 },
    outputMult: 1.5,
    upkeepMult: 1.25,
  },
  {
    cost: { credits: creditsBase * 2, alloys: alloysBase * 2, minerals: alloysBase * 4 },
    outputMult: 2.25,
    upkeepMult: 1.6,
  },
];

export const BUILDINGS: Record<BuildingId, BuildingDef> = {
  habitat: {
    id: "habitat",
    name: "Habitat Dome",
    icon: "⌂",
    description: "Pressurised dome that houses colonists.",
    cost: { credits: 150, minerals: 50 },
    upkeep: { power: 2, water: 1 },
    output: {},
    housing: 6,
    workers: 0,
    constructionSols: 3,
    storage: { food: 30, water: 30, oxygen: 30 },
    upgrades: standardUpgrades(120, 8),
    adjacency: { moralePerSameNeighbor: 1 },
  },
  solar: {
    id: "solar",
    name: "Solar Array",
    icon: "☀",
    description:
      "Photovoltaic array. Vulnerable to dust storms. Arrays next to arrays share inverters.",
    cost: { credits: 100, minerals: 30 },
    upkeep: {},
    output: { power: 5 },
    workers: 0,
    constructionSols: 2,
    upgrades: standardUpgrades(100, 6),
    adjacency: { sameType: { resource: "power", perNeighbor: 0.5, max: 2 } },
    terrainBonus: { ridge: { power: 2 } },
  },
  water_extractor: {
    id: "water_extractor",
    name: "Water Extractor",
    icon: "☃",
    description: "Drills subsurface ice and refines it into water.",
    cost: { credits: 120, minerals: 40 },
    upkeep: { power: 2 },
    output: { water: 3 },
    workers: 1,
    constructionSols: 3,
    upgrades: standardUpgrades(140, 10),
    terrainBonus: { ice: { water: 3 } },
  },
  greenhouse: {
    id: "greenhouse",
    name: "Greenhouse",
    icon: "⚘",
    description:
      "Hydroponic farm producing food. Gains a small bonus when adjacent to a Water Extractor.",
    cost: { credits: 140, minerals: 40 },
    upkeep: { power: 1, water: 1 },
    output: { food: 3 },
    workers: 1,
    constructionSols: 3,
    upgrades: standardUpgrades(150, 10),
    adjacency: {
      pair: { other: "water_extractor", resource: "food", perNeighbor: 0.5, max: 1.5 },
    },
  },
  oxygen_gen: {
    id: "oxygen_gen",
    name: "Oxygen Generator",
    icon: "♁",
    description: "Splits CO2 to generate breathable oxygen.",
    cost: { credits: 130, minerals: 50 },
    upkeep: { power: 2 },
    output: { oxygen: 3 },
    workers: 1,
    constructionSols: 3,
    upgrades: standardUpgrades(140, 10),
  },
  mine: {
    id: "mine",
    name: "Mine",
    icon: "⛏",
    description: "Extracts minerals from the regolith.",
    cost: { credits: 160, minerals: 20 },
    upkeep: { power: 2 },
    output: { minerals: 2 },
    workers: 2,
    constructionSols: 3,
    upgrades: standardUpgrades(160, 12),
    terrainBonus: { ore: { minerals: 2 } },
  },
  lab: {
    id: "lab",
    name: "Research Lab",
    icon: "⚗",
    description:
      "Generates research points. Staffed by Specialists. Labs adjacent to other labs share findings: +10% per neighbour.",
    cost: { credits: 200, minerals: 60 },
    upkeep: { power: 1 },
    output: { research: 1 },
    workers: 2,
    staffStratum: "specialists",
    constructionSols: 4,
    maintenance: { minerals: 0.2 },
    upgrades: standardUpgrades(200, 15),
    adjacency: { sameType: { resource: "research", perNeighbor: 0.1, max: 0.3 } },
  },
  foundry: {
    id: "foundry",
    name: "Alloy Foundry",
    icon: "⚒",
    description: "Smelts minerals into structural alloys. Staffed by Specialists.",
    cost: { credits: 250, minerals: 80 },
    upkeep: { power: 3, minerals: 3 },
    output: { alloys: 1 },
    workers: 2,
    staffStratum: "specialists",
    constructionSols: 5,
    maintenance: { minerals: 0.5 },
    upgrades: standardUpgrades(250, 20),
    requiresResearch: "alloy_metallurgy",
  },
  spaceport: {
    id: "spaceport",
    name: "Spaceport",
    icon: "✈",
    description:
      "Launch pad and orbital docks. Staffed by Specialists. Generates credits via interplanetary trade. Enables future off-world expansion.",
    cost: { credits: 600, minerals: 200, alloys: 20 },
    upkeep: { power: 4 },
    output: { credits: 5 },
    workers: 3,
    staffStratum: "specialists",
    constructionSols: 8,
    maintenance: { alloys: 0.25, minerals: 1 },
    upgrades: standardUpgrades(500, 30),
    requiresResearch: "spaceflight",
  },
  storage_tank: {
    id: "storage_tank",
    name: "Storage Tank",
    icon: "▥",
    description:
      "Pressurised tanks and silos. Increases your maximum storage for life-support resources and ore.",
    cost: { credits: 80, minerals: 30 },
    upkeep: {},
    output: {},
    workers: 0,
    constructionSols: 2,
    storage: { food: 250, water: 250, oxygen: 250, minerals: 300, alloys: 80, rare_earths: 60 },
    upgrades: standardUpgrades(80, 6),
  },
  barracks: {
    id: "barracks",
    name: "Barracks",
    icon: "⚔",
    description:
      "Houses and trains soldiers. Provides capacity for the colony's standing army. Foundation for future military operations.",
    cost: { credits: 180, minerals: 60, alloys: 5 },
    upkeep: { power: 1, credits: 1 },
    output: {},
    workers: 4,
    staffStratum: "soldiers",
    constructionSols: 4,
    soldierCapacity: 4,
    upgrades: standardUpgrades(180, 10),
    maintenance: { alloys: 0.1 },
    requiresResearch: "standing_army",
  },
  battery: {
    id: "battery",
    name: "Battery",
    icon: "▤",
    description:
      "Industrial chemical battery bank. Adds power storage so the colony can ride out dust storms.",
    cost: { credits: 80, minerals: 30 },
    upkeep: {},
    output: {},
    workers: 0,
    constructionSols: 2,
    storage: { power: 60 },
    upgrades: standardUpgrades(80, 6),
    requiresResearch: "battery_storage",
  },
  geothermal_plant: {
    id: "geothermal_plant",
    name: "Geothermal Plant",
    icon: "♨",
    description:
      "Taps subsurface heat. Steady power output, unaffected by dust storms.",
    cost: { credits: 220, minerals: 70, alloys: 10 },
    upkeep: {},
    output: { power: 6 },
    workers: 1,
    staffStratum: "specialists",
    constructionSols: 5,
    maintenance: { minerals: 0.5 },
    upgrades: standardUpgrades(220, 14),
    requiresResearch: "geothermal_power",
  },
  fusion_reactor: {
    id: "fusion_reactor",
    name: "Fusion Reactor",
    icon: "⚛",
    description:
      "Stable D-T fusion at colony scale. The late-game power spine.",
    cost: { credits: 1500, minerals: 300, alloys: 100, rare_earths: 50 },
    upkeep: { water: 2 },
    output: { power: 30 },
    workers: 3,
    staffStratum: "specialists",
    constructionSols: 12,
    maintenance: { alloys: 1, rare_earths: 0.5 },
    upgrades: standardUpgrades(1200, 60),
    requiresResearch: "fusion_power",
  },
  vat_farm: {
    id: "vat_farm",
    name: "Vat Farm",
    icon: "❀",
    description:
      "Cell-cultured protein and printed produce. Food without thirsty crops.",
    cost: { credits: 220, minerals: 80, alloys: 5 },
    upkeep: { power: 2 },
    output: { food: 4 },
    workers: 2,
    staffStratum: "specialists",
    constructionSols: 4,
    upgrades: standardUpgrades(220, 14),
    requiresResearch: "vat_protein",
  },
  mega_habitat: {
    id: "mega_habitat",
    name: "Mega-Habitat",
    icon: "⌬",
    description:
      "Continent-scale dome housing tens of thousands of colonists.",
    cost: { credits: 1000, minerals: 400, alloys: 60 },
    upkeep: { power: 5, water: 4 },
    output: {},
    housing: 30,
    workers: 0,
    constructionSols: 15,
    storage: { food: 80, water: 80, oxygen: 80 },
    maintenance: { alloys: 0.3 },
    upgrades: standardUpgrades(900, 40),
    requiresResearch: "megastructures",
  },
  orbital_dock: {
    id: "orbital_dock",
    name: "Orbital Dock",
    icon: "⌖",
    description:
      "Geosynchronous shipyard and tender port. The launchpad for the fleets that come in Phase 4.",
    cost: { credits: 1500, minerals: 400, alloys: 80, rare_earths: 20 },
    upkeep: { power: 6 },
    output: {},
    workers: 4,
    staffStratum: "specialists",
    constructionSols: 15,
    maintenance: { alloys: 0.5, rare_earths: 0.2 },
    upgrades: standardUpgrades(1000, 50),
    requiresResearch: "combined_arms",
  },
  atmospheric_processor: {
    id: "atmospheric_processor",
    name: "Atmospheric Processor",
    icon: "❄",
    description:
      "Terraforming megastructure. Staffed by Specialists. Slowly thickens Mars' atmosphere. At full terraform, colonists no longer need bottled oxygen.",
    cost: { credits: 2000, minerals: 500, alloys: 100 },
    upkeep: { power: 8, water: 4 },
    output: {},
    workers: 3,
    staffStratum: "specialists",
    constructionSols: 10,
    maintenance: { alloys: 0.5, minerals: 2 },
    upgrades: standardUpgrades(1500, 60),
    atmospherePerSol: 0.04,
    requiresResearch: "atmospherics",
  },
};

export const BUILDING_ORDER: BuildingId[] = [
  "habitat",
  "mega_habitat",
  "solar",
  "battery",
  "geothermal_plant",
  "fusion_reactor",
  "water_extractor",
  "greenhouse",
  "vat_farm",
  "oxygen_gen",
  "mine",
  "storage_tank",
  "lab",
  "foundry",
  "barracks",
  "spaceport",
  "orbital_dock",
  "atmospheric_processor",
];
